baseURL: "https://luanwolf.github.io/" 
title: Central Dozamigos
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Minecraft Dozamigos
          url: https://www.curseforge.com/minecraft/modpacks/dozamigos
          weight: 1
        - name: Kevin Launcher
          url: https://github.com/luanwolf/kevin-launcher/releases/tag/v1.1.0
          weight: 2
        - name: Github
          url: https://github.com/luanwolf
          weight: 3 
        - name: Papers
          url: papers/
          weight: 4
        - name: Discord Dozamigos
          url: https://discord.gg/PYkRJSFxMB
          weight: 5

params:
    description: "Central Dozamigos"
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "Fevereiro 2024"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: false
    profileMode:
          enabled: true
          title: Olá, seja bem vindo! 👋🏻
          subtitle: "Me chamo Luan, conhecido como Heyash ou 'moço do RH'. Este local é dedicado para os meus amigos terem um canal central das coisas para jogarmos."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Heyash
          buttons:
            - name: Papers
              url: papers/
              weight: 1
            - name: Minecraft Dozamigos
              url: https://www.curseforge.com/minecraft/modpacks/dozamigos
              weight: 2
            - name: Kevin Launcher
              url: https://github.com/luanwolf/kevin-launcher/releases/tag/v1.1.0
              weight: 3
            - name: Discord Dozamigos
              url: https://discord.gg/PYkRJSFxMB
              weight: 4
          socialIcons:
       #    - name: CV
       #      url: cv.pdf
       #    - name: Email
       #      url: mailto:pascal.michaillat@gmail.com
       #    - name: Location
       #     url: location/
       #   - name: Office Hours
       #       url: officehours/
       #     - name: Google Scholar
       #       url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
       #     - name: YouTube
       #       url: https://www.youtube.com/@pmichaillat
           - name: GitHub
              url: https://github.com/luanwolf
       #     - name: Substack
       #        url: https://pmichaillat.substack.com
           - name: Twitter
              url: https://twitter.com/luanrafaelwolf

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Central Dozamigos"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
